# This project requires the following ruby gems, buildr addons
gems:
  # Suppose we want to notify developers when testcases fail.
  #- buildr-twitter-notifier-addon >=1
  # we test with ruby mock objects
  #- mocha
  #- ci_reporter

# The artifact declarations will be automatically loaded by buildr, so that
# you can reference artifacts by name (a ruby-symbol) on your buildfile.
artifacts:
  spring: org.springframework:spring:jar:2.0
  log4j: log4j:log4j:jar:1.0
  j2ee: geronimo-spec:geronimo-spec-j2ee:jar:1.4-rc4

# Of course project settings can be defined here
#twitter:
#  notify:
#    test_failure: unless-modified
#    compile_failure: never
#  developers:
#    - joe
#    - jane
#
#jira:
#  uri: https://jira.corp.org