source 'http://rubygems.org'
gem 'cucumber'
gem 'rest-client'
gem 'ruby-debug-base'
gem 'ruby-debug-ide', '~> 0.4.17.beta9'
gem 'activerecord'
gem 'rspec-expectations'
gem 'jruby-openssl'
gem 'compass'
gem 'bootstrap-sass', '~> 2.0.4.0'
gem 'term-ansicolor'